# Builds SEAPATH and uploads SBOM artifacts.
# This is a reusable workflow that cannot be launched directly.
---
name: Build (internal)

on:
  workflow_call:
    inputs:
      origin_repository:
        type: string
        required: true
        description: Repository that triggered this workflow dispatch.
      origin_sha:
        type: string
        required: true
        description: >-
          Value of the GITHUB_SHA variable for the workflow on the
          origin repository.

# This is absolutely crazy but Action Variables are not accessible to runs
# triggered by PRs from forks repository (https://github.com/orgs/community/discussions/44322).
# Thus, we avoid all use of Action Variables in the pr workflow and the ones
# called by it (_build and _cve-check) and we hardcode the values here.
# It makes developing the CI itself a pain but there is no real good solution.
env:
  REPO_MANIFEST_REPOSITORY: 'SEAPATH/repo-manifest'
  REPO_MANIFEST_NAME: 'wrynose.xml'

jobs:
  build:
    runs-on: ["self-hosted", "runner-sfl-seapath"]
    # This job may check out potentially unsafe user code from Pull Requests.
    # Giving it only the necessary permissions mitigates potential token misuse
    # introduced in user code.
    # The only step using the GitHub API is the "upload artifacts" one, which
    # seems to only need the "contents: read" permission as per [1]
    # [1] https://github.com/actions/upload-artifact/issues/197#issuecomment-3154708082
    permissions:
      contents: read
    strategy:
      fail-fast: true # TODO eventually set to false
      max-parallel: 1
      matrix:
        # Hardcoded due to GH Actions limitation on vars (see above)
        cqfd_flavor: ["host_efi", "host_standalone_efi", "guest_efi", "observer_efi"]
    env:
      WORKSPACE: workspace-bitbake
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      # We clean the workspace at the beginning and not at the end
      # to easily debug failed runs
      - name: Clean workspace
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf ${{ env.WORKSPACE }}

      - name: Create workspace
        working-directory: ${{ github.workspace }}
        run: mkdir -p ${{ env.WORKSPACE }}

      - name: Init repo
        run: |
          repo init \
            -u "${{ github.server_url }}/${{ env.REPO_MANIFEST_REPOSITORY }}" \
            -b "${{ case(inputs.origin_repository == env.REPO_MANIFEST_REPOSITORY, inputs.origin_sha, 'HEAD') }}" \
            -m "${{ env.REPO_MANIFEST_NAME }}"
          repo sync

      - name: Checkout specific ref
        if: inputs.origin_repository != env.REPO_MANIFEST_REPOSITORY
        env:
          ORIGIN_REPOSITORY: ${{ inputs.origin_repository }}
        run: |
          repo_name=${ORIGIN_REPOSITORY#*/} # this removes the '<organization>/' prefix
          path=$(repo list | awk -v repo_name="$repo_name" -F ' : ' '$2 == repo_name {print $1}')
          echo "Checking out specific revision for git repo "$repo_name" at "$path"..."

          cd "$path"
          # repo only creates 1 remote so no problem here
          remote=$(git remote)

          git fetch "$remote" "${{ inputs.origin_sha }}"
          git checkout FETCH_HEAD

      - name: Init build system
        run: |
          cqfd init
          touch "keys/ansible_public_ssh_key.pub"
          cp seapath.conf.sample seapath.conf

      - name: Build ${{ matrix.cqfd_flavor }}
        run: |
          # Since we are in a non-interactive bash, the bashrc file is not
          # read and CQFD environment variables are not used, especially the
          # Yocto cache -related ones... Thus we source the bashrc file.
          source /etc/bash.bashrc
          cqfd -b ${{ matrix.cqfd_flavor }}

      - name: Upload SBOM files
        uses: actions/upload-artifact@v6
        with:
          name: sbom-${{ matrix.cqfd_flavor }}
          path: |
            ${{ env.WORKSPACE }}/build/tmp/deploy/images/**/*.rootfs.json
            ${{ env.WORKSPACE }}/build/tmp/deploy/images/**/*.rootfs.spdx.tar.zst
          if-no-files-found: warn

      # We clean the image directory at the end so we don't pollute
      # future workflows artifacts since in the above step we don't
      # filter the artifacts we upload.
      - name: Clean image deploy directory
        if: always()
        run: |
          # see comment above
          source /etc/bash.bashrc
          cqfd -b ${{ matrix.cqfd_flavor }} run -c --clean-image
