name: Pull Requests

on:
  pull_request:
    branches:
      - scarthgap
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - .github/**/*

  # See dispatch explanation in push.yml.
  workflow_dispatch:
    inputs:
      origin_repository:
        type: string
        required: true
        description: Repository that triggered this workflow dispatch.
      origin_sha:
        type: string
        required: true
        description: >-
          Value of the GITHUB_SHA variable for the workflow on the
          origin repository.
      origin_run_id:
        type: number
        required: true
        description: ID of the delegating workflow run.
      origin_pr_number:
        type: number
        required: true
        description:
          Number of the PR that originally triggered the workflow.

run-name: "PR #${{ inputs.origin_pr_number || github.event.pull_request.number }} at ${{ inputs.origin_repository || github.repository }}"

permissions: read-all

jobs:
  notice:
    name: Display notice
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    runs-on: ["ubuntu-slim"]
    steps:
      - name: Display notice
        run: |
          echo "::notice::This workflow has been delegated by the ${{ inputs.origin_repository }} repository. See the delegating workflow at ${{ github.server_url }}/${{ inputs.origin_repository }}/actions/runs/${{ inputs.origin_run_id }}."
          echo "::notice::See the pull request at ${{ github.server_url }}/${{ inputs.origin_repository }}/pull/${{ inputs.origin_pr_number }}"

  call-build:
    name: Call Build workflow
    uses: ./.github/workflows/_build.yml
    with:
      origin_repository: "${{ inputs.origin_repository || github.repository }}"
      origin_sha: "${{ inputs.origin_sha || github.sha }}"

  call-cve-check:
    name: Call CVE check workflow
    needs: call-build
    uses: ./.github/workflows/_cve-check.yml
    with:
      build-run-id: ${{ github.run_id }}

  process-results:
    if: always()
    name: Process results
    needs:
      - call-build
      - call-cve-check
    runs-on: ["ubuntu-slim"]
    env:
      PR_RESULTS_FILE: pr_results.json
    steps:
      - name: Create results file
        run: |
          cat <<EOF > ${{ env.PR_RESULTS_FILE }}
          {
            "pr_number": ${{ inputs.origin_pr_number || github.event.pull_request.number }},
            "pr_repository": "${{ inputs.origin_repository || github.repository }}",
            "build_result": "${{ needs.call-build.result }}",
            "cve_check_result": "${{ needs.call-cve-check.result }}",
            "cve_detected": "${{ needs.call-cve-check.outputs.cve-detected }}"
          }
          EOF

      - name: Upload results artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: "${{ env.PR_RESULTS_FILE }}"
          retention-days: 1

      - name: Fail job if CVE detected
        if: "${{ needs.call-cve-check.outputs.cve-detected == 'true' }}"
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed("Vulnerabilities triggered the fail condition for your build.")
